<%--
  Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  The ASF licenses this file to You
  under the Apache License, Version 2.0 (the "License"); you may not
  use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.  For additional information regarding
  copyright in this work, please see the NOTICE file in the top level
  directory of this distribution.
--%>
<%@ include file="/WEB-INF/jsps/taglibs-spring.jsp" %>

<h3><spring:message code="mainPage.actions"/></h3>
<hr/>

<p>
    <%-- <button>, not <a>: a control that triggers a JS action rather than
         navigating should be a button (a11y sweep). id="addCategoryButton"
         is what CategoryIT keys on now that Categories.jsp's own empty-state
         button is also a <button> and element type can no longer
         disambiguate the two. showCategoryAddModal() itself carries no
         author-controlled text, so it stays a plain onclick call. --%>
    <button type="button" id="addCategoryButton" class="btn btn-link p-0 align-baseline border-0" onclick="showCategoryAddModal()">
        <span class="bi bi-plus-lg" aria-hidden="true"></span>
        <spring:message code="categoriesForm.addCategory"/>
    </button>
</p>

<script>

    function showCategoryAddModal() {

        feedbackAreaEdit.html("");
        $('#category-edit-title').html('<spring:message code="categoryForm.add.title"/>');

        // categoryField() lives in Categories.jsp, which always renders this
        // sidebar. It reaches the inputs by name; the ids these lines used to
        // use (#categoryEditForm_bean_name and friends) were generated by
        // Struts and no longer exist, so clearing the form did nothing and Add
        // opened showing whatever was last in it -- when it opened at all.
        categoryField('bean.id').val("");
        categoryField('bean.name').val("");
        categoryField('bean.description').val("");
        categoryField('bean.image').val("");

        validateCategory();

        bootstrap.Modal.getOrCreateInstance(document.getElementById('category-edit-modal')).show();
    }

    <%-- Focus has to wait for shown.bs.modal: Bootstrap animates the dialog
         in, and an element inside a display:none subtree cannot take focus.
         Bound once on the element, not per open. --%>
    $(document).ready(function () {
        $('#category-edit-modal').on('shown.bs.modal', function () {
            categoryField('bean.name').trigger('focus');
        });
    });

</script>

