server.servlet.context-path=/roller
server.port=8080
spring.servlet.multipart.max-file-size=1000000000B
spring.servlet.multipart.max-request-size=1000000000B
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.error.whitelabel.enabled=false
management.endpoints.web.exposure.include=health
spring.devtools.livereload.enabled=false
